version: "3.5"

services:
    apid:
        #image: apid
        image: ghcr.io/byeol-i/battery-level-checker--apid:latest
        networks:
            - kafka-network
            - traefik-network
        environment:
            - TZ=Asia/Seoul
        deploy:
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 10s
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-network
                - traefik.http.routers.battery-api.rule=Host(`api.${Domain1}`)
                - traefik.http.routers.battery-api.middlewares=redirect-to-https
                - traefik.http.routers.battery-api.entrypoints=web
                - traefik.http.services.battery-api.loadbalancer.server.port=80
                - traefik.http.routers.battery-api--https.rule=Host(`api.${Domain1}`)
                - traefik.http.routers.battery-api--https.tls=true
                - traefik.http.routers.battery-api--https.tls.certresolver=myresolver
                - traefik.http.routers.battery-api--https.entrypoints=websecure
            placement:
                constraints: [node.role==worker]
    auth:
        image: ghcr.io/byeol-i/battery-level-checker--auth:latest
        networks:
            - kafka-network
        secrets:
            - firebase-key
        environment:
            - SWARM="true"
            - TZ=Asia/Seoul
        deploy:
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 10s
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints: [node.role==worker]
    db:
        image: ghcr.io/byeol-i/battery-level-checker--db:latest
        networks:
            - kafka-network
        environment:
            - DB_PRIMARY_ADDR=pgmaster
            - DB_PRIMARY_PORT=5432
            - DB_REPLICA_ADDR=pgslave
            - DB_REPLICA_PORT=5432
            - DB_USER=table_admin
            - DB_PASSWORD=HelloWorld
            - DB_NAME=battery
            - TZ=Asia/Seoul
        deploy:
            placement:
                constraints: [node.role==worker]
    # consumer:
    #     image: ghcr.io/byeol-i/battery-level-checker--consumer:latest
    #     networks:
    #         - kafka-network
    #     deploy:
    #         placement:
    #             constraints: [node.role==worker]

networks:
    kafka-network:
        external: true
    traefik-network:
        external: true

secrets:
    firebase-key:
        file: ./conf/firebase/key.json
    # firebase-key:
    #     external: true
