version: "3"

services:
   apid:
        image: apid
        # image: ghcr.io/byeol-i/battery-level-checker-apid:latest
        networks:
            - kafka-network
            - traefik-network
        deploy:
          labels:
              - traefik.enable=true
              - traefik.docker.network=traefik-network
              - traefik.http.routers.api-testapp.rule=Host(`api.${Domain1}`) # http setting
              - traefik.http.routers.api-testapp.entrypoints=web # open to :80
              - traefik.http.services.api-testapp.loadbalancer.server.port=80 # listening port
          placement:
            constraints: [node.role==manager]
networks:
    kafka-network:
      external: true
    traefik-network:
      external: true
