version: "3"

services:
   apid:
        image: ghcr.io/aglide100/battery-level-checker-apid:latest
        networks:
            - traefik-network
            - default
              #ports:
              #- "5999:80"
        deploy:
          labels:
              - traefik.enable=true
              - traefik.docker.network=traefik-network
              - traefik.http.routers.api-testapp.rule=Host(`api.${Domain1}`) # http setting
              - traefik.http.routers.api-testapp.entrypoints=web # open to :80
              - traefik.http.services.api-testapp.loadbalancer.server.port=80 # listening port
networks:
    traefik-network:
        external: true
