version: "3.3"

services:
    apid:
        #image: apid
        image: ghcr.io/byeol-i/battery-level-checker--apid:latest
        networks:
            - kafka-network
            - traefik-network
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-network
                - traefik.http.routers.battery-api.rule=Host(`api.${Domain1}`)
                - traefik.http.routers.battery-api.middlewares=redirect-to-https
                - traefik.http.routers.battery-api.entrypoints=web
                - traefik.http.services.battery-api.loadbalancer.server.port=80
                - traefik.http.routers.battery-api--https.rule=Host(`api.${Domain1}`)
                - traefik.http.routers.battery-api--https.tls=true
                - traefik.http.routers.battery-api--https.tls.certresolver=myresolver
                - traefik.http.routers.battery-api--https.entrypoints=websecure
                #- traefik.http.routers.battery-api.tls.certresolver=le
            placement:
              constraints: [node.role==worker]
    auth:
        image: ghcr.io/byeol-i/battery-level-checker--auth:latest
        networks:
            - kafka-network
            - traefik-network
        secrets:
            - firebase-key
        deploy:
            placement:
              constraints: [node.role==worker]

networks:
    kafka-network:
        external: true
    traefik-network:
        external: true


secrets:
    firebase-key:
        file: ./conf/firebase/key.json
    # firebase-key:
    #     external: true