version: "3"

services:
    pgmaster:
        image: ghcr.io/byeol-i/battery-level-checker--postgresql-primary:latest
        hostname: pgmaster
        networks:
            - kafka-network
        ports:
            - "5432:5432"
        volumes:
            - /media/pi/OS3/container-config/battery/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: battery
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
            TZ: Asia/Seoul
            # PGDATA: /var/lib/postgresql
        deploy:
            placement:
                constraints:
                    - node.role == manager
    pgslave:
        image: ghcr.io/byeol-i/battery-level-checker--postgresql-replica:latest
        networks:
            - kafka-network
        ports:
            - "8432:5432"
        volumes:
            # must be empty, when deleting postgres file in container shell, permission should be stuck...
            - /home/data/battery/data:/var/lib/postgresql/data:z
        environment:
            POSTGRES_DB: battery
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
            PGDATA: /var/lib/postgresql/data
            TZ: Asia/Seoul
volumes:
    postgres-vol:

networks:
    kafka-network:
        external: true
