version: "3.3"

services:
    primary:
        image: ghcr.io/aglide100/battery-level-checker-db-primary:latest
        command: postgres -c log_destination=stderr -c log_statement=all
        volumes:
            - pg-primary-vol:/var/lib/postgresql/data
        hostname: primary-db
        networks:
            - kafka-network
        ports:
            - "5432"
        environment:
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
        deploy:
            placement:
                constraints:
                    - node.role == manager
    replica:
        image: ghcr.io/aglide100/battery-level-checker-db-replica:latest
        command: postgres -c log_destination=stderr -c log_statement=all
        volumes:
            - pg-replica-vol:/var/lib/postgresql/data
        hostname: replica-db
        networks:
            - kafka-network
        ports:
            - "5432"
        depends_on:
            - primary
        environment:
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
        deploy:
            placement:
                constraints:
                    - node.role == worker
networks:
    kafka-network:
        external: true

volumes:
    pg-primary-vol:
    pg-replica-vol:
