version: "3"

services:
    pgmaster:
        image: ghcr.io/byeol-i/battery-level-checker--postgresql-primary:latest
        hostname: pgmaster
        networks:
            - kafka-network
        ports:
            - "5432:5432"
        volumes:
            - /media/pi/OS3/container-config/battery/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: battery
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
            # PGDATA: /var/lib/postgresql
        deploy:
            placement:
                constraints:
                    - node.role == manager
    pgslave:
        image: ghcr.io/byeol-i/battery-level-checker--postgresql-replica:latest
<<<<<<< HEAD
        command:
            [
                "sh",
                "-c",
                "while ! pg_isready -h pgmaster; do sleep 2; done; /bin/bash /docker-entrypoint-initdb.d/init.sh",
            ]
=======
        # command:
        #     [
        #         "sh",
        #         "-c",
        #         "while ! pg_isready -h pgmaster; do sleep 2; done; /bin/bash /docker-entrypoint-initdb.d/init.sh",
        #     ]
>>>>>>> 1dbbe89bca8f25fdfc4a24eb85e2aad150a4fed7
        networks:
            - kafka-network
        ports:
            - "8432:5432"
        volumes:
            - postgres-vol:/var/lib/postgresql/data:z
        environment:
            POSTGRES_DB: battery
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
            PGDATA: /var/lib/postgresql/data
volumes:
    postgres-vol:

networks:
    kafka-network:
        external: true
