version: "3.3"

services:
  db--primary:
    # image: postgres:11-alpine
    image: ghcr.io/byeol-i/battery-level-checker--postgresql-primary:latest
    volumes:
      - pg-primary-vol:/var/lib/postgresql/data
    hostname: primary-db
    networks:
      - kafka-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: battery
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: HelloWorld
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    deploy:
      placement:
        constraints:
          - node.role == manager
  db--replica:
    # image: postgres:11-alpine
    image: ghcr.io/byeol-i/battery-level-checker--postgresql-replica:latest
    volumes:
      - pg-replica-vol:/var/lib/postgresql/data
    hostname: replica-db
    networks:
      - kafka-network
    ports:
      - "8432:5432"
    depends_on:
      - db--primary
    environment:
      POSTGRES_DB: battery
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: HelloWorld
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role == worker
networks:
  kafka-network:
    external: true

volumes:
  pg-primary-vol:
  pg-replica-vol:
