version: "3"

services:
    consumer:
        build:
            context: .
            dockerfile: cmd/consumer/Dockerfile
        networks:
            - kafka-network
        environment:
            - TZ=Asia/Seoul
    producer:
        build:
            context: .
            dockerfile: testing/Dockerfile
        networks:
            - kafka-network
        environment:
            - TZ=Asia/Seoul

networks:
    kafka-network:
        external: true
