version: "3"

services:
    apid:
        build:
            context: .
            dockerfile: cmd/apid/Dockerfile
        networks:
            - kafka-network
        ports:
            - 80:80
        environment:
            - TZ=Asia/Seoul
        command: "/opt/bin/app/main -usingAuth=false"
    consumer:
        build:
            context: .
            dockerfile: cmd/consumer/Dockerfile
        networks:
            - kafka-network
        environment:
            - TZ=Asia/Seoul
        command: "/opt/bin/app/main -brokerList=kafka-1:9094 -numOfReplicationFactor=1 -numOfPartitions=1"
    # auth:
    #     build:
    #         context: .
    #         dockerfile: cmd/auth/Dockerfile
    #     hostname: battery_auth
    #     networks:
    #         - kafka-network
    #     environment:
    #         - TZ=Asia/Seoul
    #     command: "/opt/bin/app/main"
    cache:
        build:
            context: .
            dockerfile: cmd/cache/Dockerfile
        hostname: battery_cache
        networks:
            - kafka-network
        ports:
            - 50015:50015
        environment:
            - TZ=Asia/Seoul
        command: "/opt/bin/app/main"
    db:
        build:
            context: .
            dockerfile: cmd/db/Dockerfile
        hostname: battery_db
        networks:
            - kafka-network
        ports:
            - 50012:50012
        environment:
            - DB_PRIMARY_ADDR=pgmaster
            - DB_PRIMARY_PORT=5432
            - DB_REPLICA_ADDR=pgslave
            - DB_REPLICA_PORT=5432
            - DB_USER=table_admin
            - DB_PASSWORD=HelloWorld
            - DB_NAME=battery
            - TZ=Asia/Seoul
        command: "/opt/bin/app/main"

networks:
    kafka-network:
        external: true
