version: "3"

services:
    apid:
        build:
            context: .
            dockerfile: cmd/apid/Dockerfile
        networks:
            - kafka-network
        ports:
            - 80:80
        environment:
            - TZ=Asia/Seoul
        command: "/opt/bin/app/main -usingAuth=false"

networks:
    kafka-network:
        external: true
