version: "3"

services:
    # apid:
    #     container_name: apid
    #     image: apid:latest
    #     networks:
    #         - kafka-network
    # producer:
    #     container_name: producer
    #     image: producer:latest
    #     networks:
    #         - kafka-network
    # consumer:
    #     container_name: consumer
    #     image: consumer:latest
    #     networks:
    #         - kafka-network

    primary:
        image: ghcr.io/aglide100/battery-level-checker-db-primary:latest
        command: postgres -c log_destination=stderr -c log_statement=all
        hostname: primary-db
        ports:
            - "5432"
        environment:
            POSTGRES_USER: table_admin
            POSTGRES_PASSWORD: HelloWorld
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
    zookeeper:
        container_name: local-zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
            - "2181:2181"
    kafka-1:
        container_name: local-kafka
        image: wurstmeister/kafka:2.12-2.3.0
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "test_topic:1:1" # Topic명:Partition개수:Replica개수
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    kafka-network:
        external: true
