version: "3.4"

services:
    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            GF_PATHS_DATA: /var/lib/grafana
            GF_SECURITY_ADMIN_PASSWORD: kafka
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        container_name: grafana
        depends_on:
            - prometheus
        deploy:
            placement:
                constraints: [node.role==manager]

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: "--config.file=/etc/prometheus/prometheus.yml"
        container_name: prometheus
        deploy:
            placement:
                constraints: [node.role==manager]

    kafka_manager:
        image: scjtqs/kafka-manager
        networks:
            - kafka-network
        ports:
            - target: 9000
              published: 9000
              protocol: tcp
              mode: host
        environment:
            ZK_HOSTS: "zoo1:2181,zoo2:2182"
            APPLICATION_SECRET: "random-secret"
        deploy:
            placement:
                constraints: [node.role==manager]

networks:
    kafka-network:
        external: true
