version: "3.4"

services:
    kafka_manager:
        image: scjtqs/kafka-manager
        networks:
            - kafka-network
        ports:
            - "9000:9000"
        labels:
            - "traefik.enable=false"
        environment:
            ZK_HOSTS: "zoo1:2181"
            # ZK_HOSTS: "zoo1:2181,zoo2:2182,zoo3:2183"
            APPLICATION_SECRET: "random-secret"
            TZ: Asia/Seoul
        deploy:
            placement:
                constraints: [node.role==manager]

networks:
    kafka-network:
        external: true
