version: "3.4"

services:
    kafka_manager:
        image: scjtqs/kafka-manager
        networks:
            - kafka-network
        ports:
            - target: 9000
              published: 9000
              protocol: tcp
              mode: host
        environment:
            ZK_HOSTS: "zoo1:2181,zoo2:2182,zoo3:2183"
            APPLICATION_SECRET: "random-secret"
        deploy:
            placement:
                constraints: [node.role==manager]

networks:
    kafka-network:
        external: true
