version: "3.0"

services: 
  certbot:
      container_name: certbot
      image: certbot/certbot:arm64v8-nightly
      command: certonly --standalone --email ${Email} --agree-tos --no-eff-email -d ${Domain1} -d jellyfin.${Domain1} -d jellyfin2.${Domain1} -d nextcloud.${Domain1} -d code.${Domain1} -d api.${Domain1}
      #command: certonly --webroot --webroot-path=/var/www/certbot --email ${Email} --agree-tos --no-eff-email -d ${Domain1} -d jellyfin.${Domain1} -d jellyfin2.${Domain1} -d nextcloud.${Domain1} -d code.${Domain1}
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /home/data/www/certbot:/var/www/certbot
          #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
