version: '3'

services:
  pgmaster:
    image: ghcr.io/byeol-i/battery-level-checker--postgresql-primary:latest
    hostname: master
    networks:
        - kafka-network
    # ports:
    #   - "5432:5432"
    volumes:
      - /media/pi/OS3/contaner-config/battery/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: battery
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: HelloWorld
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      # PGDATA: /var/lib/postgresql
    deploy:
      placement:
        constraints:
          - node.role == manager
  pgslave:
    image: ghcr.io/byeol-i/battery-level-checker--postgresql-replica:latest
    networks:
        - kafka-network
    # ports:
    #   - "8432:5432"
    volumes:
        - /home/data/battery/data:/var/lib/postgresql/data
    links:
      - pgmaster:master
    environment:
      POSTGRES_DB: battery
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: HelloWorld
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      PGDATA: /var/lib/postgresql/data
volumes:
  postgres-vol:

networks:
    kafka-network:
        external: true
