name: build-db-image

on:
    push:
        branches:
            - "master"

jobs:
    buildPrimaryImage:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                appname:
                    - primary
                    - replica
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./cmd/db/Dockerfile.${{ matrix.appname }}
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/byeol-i/battery-level-checker--postgresql-${{ matrix.appname }}:latest
